eps: 0.5
flat_hand: false
gesture_extractor_args:
  do_cluster: true
  hid_dim:
  - 36
  - 72
  - 144
  in_channels: 2
  num_g3d_scales: 3
  num_gcn_scales: 3
  num_point: 21
gesture_extractor_cls: signbert.model.MSG3DGestureExtractor.GestureExtractor
hand_cluster: true
in_channels: 2
lmbd: 0.01
lr: 0.001
means_fpath: /home/tmpvideos/SLR/HANDS17/preprocess/means.npy
n_pca_components: 11
normalize_inputs: true
num_heads: 4
num_hid: 144
pct_start: null
stds_fpath: /home/tmpvideos/SLR/HANDS17/preprocess/stds.npy
tformer_dropout: 0.25
tformer_n_layers: 1
total_steps: null
use_onecycle_lr: false
use_pca: true
weight_beta: 200.0
weight_decay: 0.01
weight_delta: 200.0
