lr: 1.0e-3
batch_size: 32

datamodule_args:
  normalize: True

head_args:
  num_classes: 100
  arms_extractor_cls: signbert.model.ArmsExtractor.ArmsExtractor
  arms_extractor_args:
    in_channels: 2
    hid_dim: 144
    dropout: 0.1
  